apiVersion: "ai.sap.com/v1alpha1"
kind: ServingTemplate
metadata:
  name: genai-sustena-app
spec:
  containers:
    - image: docker.io/library/genai-sustena:latest
      name: genai
      ports:
        - containerPort: 8080
          protocol: TCP
